In [1]:
import pandas as pd

In [3]:
df = pd.read_csv("D:\senti_pro\ECommerce\\reviews.csv")

In [4]:
df

,review,user,verification,date,length
0,After using Samsung Galaxy S23 Ultra for quite...,Aditya Sharma,Verified Purchase,2023-05-07,3813
1,I'll keep it short and direct.-Great in hand f...,Prasada reddy padala,Verified Purchase,2023-07-03,928
2,Very good smart phone with in budget Specially...,Aditya Sharma,Verified Purchase,2023-05-07,74
3,"Great camera, OS, build quality. Overall a gre...",Aditya Sharma,Verified Purchase,2023-12-02,63
4,"First of all, this was my last smartphone purc...",Sukoon Sharma,Verified Purchase,2024-01-20,790
...,...,...,...,...,...
95,English (Automated),NaN,Verified Purchase,2023-06-30,19
96,default,NaN,Verified Purchase,2023-05-07,7
97,", selected",zuhaib parvez,Verified Purchase,2023-07-03,10
98,Fullscreen,Aditya Sharma,Verified Purchase,2023-04-04,10
99,Already put my sim and writing review from thi...,Prasada reddy padala,Verified Purchase,2023-07-01,301